### PR TITLE
Bugfix/rollup broken by require

### LINKED ISSUE #255: Breaking changes make AEM Build crah with patch version
bildschirmfoto 2018-09-13 um 09 32 40

[scripts:build] ModuleNotFoundError: Module not found: Error: Can't resolve './components/App' in '/var/opt/jet/jenkins-ch-prod-node-3-lxfjet21/workspace/aem_core-it_dev_nightly/frontend-lib/node_modules/@axa-ch/aletheia/lib'

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #255 

Changes in this PR:

- [x] replaced `require` with dynamic `import()`s
- [x] enabled [experimental](https://rollupjs.org/guide/en#experimental-options) [dynamic imports for rollup](https://rollupjs.org/guide/en#dynamic-import)
- [x] set [`webpackMode` to `'eager'` for those dynamic imports](https://webpack.js.org/api/module-methods/) (to disable code splitting for them)
- [x] use babel plugins for dead code eleminiation

### CODE REVIEW

**Comment by AndyOGo** [comment]
Damn, rollup can't deal with it again...

```sh
Error: Could not resolve './screens/mfAuswahlFahrzeug' from src/test/_config.js
Error: Could not resolve './screens/mfAuswahlFahrzeug' from src/test/_config.js
    at error (/home/travis/build/axa-ch/aletheia/node_modules/rollup/dist/rollup.js:199:15)
    at /home/travis/build/axa-ch/aletheia/node_modules/rollup/dist/rollup.js:20674:25
    at <anonymous>
```

**Comment by AndyOGo** [comment]
At @LucaMele  the rollup build would only work if the excluded test files from `src/test/` are present (same case as before).
I meant that travis is again broken...

**Comment by AndyOGo** [comment]
because dynamic imports aren't tree shaken by rollup 😭 
https://github.com/rollup/rollup/issues/2284

**Comment by LucaMele** [comment]
yes we need to find a solution and i know is not easy and quick to solve

**Comment by LucaMele** [comment]
so is in your interest to fix first AEM build and then travis ;)

**Comment by AndyOGo** [comment]
I added now dead code elemination through babel, to work around buggy and different behaviour of rollup's and webpack's tree shaking...

https://www.npmjs.com/package/babel-plugin-minify-dead-code-elimination
https://www.npmjs.com/package/babel-plugin-minify-guarded-expressions

**Comment by AndyOGo** [comment]
I tested running with webpack i.e. `npm run start` and building with rollup i.e. `npm run build`.
My `lib/aletheia.es.js` file doesn't include `AppTest` now 👍

**Comment by AndyOGo** [comment]
@LucaMele 
@lina-salih 
We can only merge this if yesterdays release from lina is finished!

**Comment by LucaMele** [comment]
@AndyOGo we just finishing the SSO setup togehter

**Comment by AndyOGo** [comment]
@LucaMele I could not test if the `lib/` esm build will work as expected

**Comment by AndyOGo** [comment]
@LucaMele 
@lina-salih 
This is ready to be merged, though dynamic ES imports are still an experimental feature of rollup 🤔

**Pull request merged**
