### PR TITLE
should fix css collision

### LINKED ISSUE #150: Class collition and Styleguide NOT correctly implemented for Select
The dropdown is not correctly implemented according to the styleguide but it uses as class name the patterns-library class name for dropdown and therefore it collides with the aem css and makes the options massive. colliding class: `m-dropdown__select`

bildschirmfoto 2018-05-23 um 14 34 12

bildschirmfoto 2018-05-23 um 14 34 27

bildschirmfoto 2018-05-23 um 14 34 37

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #150

### CODE REVIEW

**Comment by LucaMele** [comment]
otherwise it can still collide if another component is called like that. All CSS classes of aletheia should begin with `o-aletheia` IMHO

**Comment by AndyOGo** [comment]
@LucaMele 
Regarding components I disagree to prefix them as organisms.
I would rather have components as molecules.
Though you are completely right, that `m-dropdown` collides with `m-dropdown` of the patterns-lib.

**Comment by LucaMele** [comment]
yes possible but not BEM like. Block is `o-aletheia` and element is BLOCK + SEPARATOR + ELEMENT name therefore `o-aletheia` + `__` + `dropdown--react-select`

**Comment by LucaMele** [comment]
http://getbem.com/naming/

**Comment by LucaMele** [comment]
AH stop, you are right

**Comment by LucaMele** [comment]
Yes BLOCK is NOT `o-aletheia` but `aletheia`. `o-` is our beloging naming

**Comment by LucaMele** [comment]
Sorry, absolutly, go with your suggestion

**Pull request merged**
